//! Generated by `zig build update-model-catalog`; do not edit directly.

const std = @import("std");
const catalog = @import("model_catalog.zig");
pub const version: u32 = 1;
pub const updated_at = "2026-08-16";

pub const entries = [_]catalog.Entry{
    .{
        .identity = .{ .provider = "openai", .model = "gpt-5.6-sol" },
        .protocol_id = "openai-responses",
        .aliases = &.{"gpt-5.6"},
        .source_url = "https://developers.openai.com/api/docs/models/gpt-5.6-sol",
        .profile = .{
            .capabilities = .initMany(&.{ .streaming, .tools, .parallel_tool_calls, .thinking }),
            .settings = .initMany(&.{ .max_output_tokens, .reasoning_effort }),
            .reasoning_efforts = .initMany(&.{ .low, .medium, .high }),
            .context_window = 1050000,
            .max_output_tokens = 128000,
        },
    },
    .{
        .identity = .{ .provider = "openai-codex", .model = "gpt-5.3-codex-spark" },
        .protocol_id = "openai-codex-responses",
        .aliases = &.{},
        .source_url = "https://github.com/badlogic/pi-mono/commit/73414d08b94d7db46d3fa66582c8fe3b02dabf72",
        .profile = .{
            .capabilities = .initMany(&.{ .streaming, .tools, .parallel_tool_calls, .thinking }),
            .settings = .initMany(&.{.reasoning_effort}),
            .reasoning_efforts = .initMany(&.{ .minimal, .low, .medium, .high }),
            .context_window = 128000,
            .max_output_tokens = 128000,
        },
    },
    .{
        .identity = .{ .provider = "openai-codex", .model = "gpt-5.4" },
        .protocol_id = "openai-codex-responses",
        .aliases = &.{},
        .source_url = "https://github.com/badlogic/pi-mono/commit/73414d08b94d7db46d3fa66582c8fe3b02dabf72",
        .profile = .{
            .capabilities = .initMany(&.{ .streaming, .tools, .parallel_tool_calls, .thinking }),
            .settings = .initMany(&.{.reasoning_effort}),
            .reasoning_efforts = .initMany(&.{ .minimal, .low, .medium, .high }),
            .context_window = 272000,
            .max_output_tokens = 128000,
        },
    },
    .{
        .identity = .{ .provider = "openai-codex", .model = "gpt-5.4-mini" },
        .protocol_id = "openai-codex-responses",
        .aliases = &.{},
        .source_url = "https://github.com/badlogic/pi-mono/commit/73414d08b94d7db46d3fa66582c8fe3b02dabf72",
        .profile = .{
            .capabilities = .initMany(&.{ .streaming, .tools, .parallel_tool_calls, .thinking }),
            .settings = .initMany(&.{.reasoning_effort}),
            .reasoning_efforts = .initMany(&.{ .minimal, .low, .medium, .high }),
            .context_window = 272000,
            .max_output_tokens = 128000,
        },
    },
    .{
        .identity = .{ .provider = "openai-codex", .model = "gpt-5.5" },
        .protocol_id = "openai-codex-responses",
        .aliases = &.{},
        .source_url = "https://github.com/badlogic/pi-mono/commit/73414d08b94d7db46d3fa66582c8fe3b02dabf72",
        .profile = .{
            .capabilities = .initMany(&.{ .streaming, .tools, .parallel_tool_calls, .thinking }),
            .settings = .initMany(&.{.reasoning_effort}),
            .reasoning_efforts = .initMany(&.{ .minimal, .low, .medium, .high }),
            .context_window = 272000,
            .max_output_tokens = 128000,
        },
    },
    .{
        .identity = .{ .provider = "openai-codex", .model = "gpt-5.6-luna" },
        .protocol_id = "openai-codex-responses",
        .aliases = &.{},
        .source_url = "https://github.com/badlogic/pi-mono/commit/73414d08b94d7db46d3fa66582c8fe3b02dabf72",
        .profile = .{
            .capabilities = .initMany(&.{ .streaming, .tools, .parallel_tool_calls, .thinking }),
            .settings = .initMany(&.{.reasoning_effort}),
            .reasoning_efforts = .initMany(&.{ .minimal, .low, .medium, .high }),
            .context_window = 272000,
            .max_output_tokens = 128000,
        },
    },
    .{
        .identity = .{ .provider = "openai-codex", .model = "gpt-5.6-sol" },
        .protocol_id = "openai-codex-responses",
        .aliases = &.{},
        .source_url = "https://github.com/badlogic/pi-mono/commit/73414d08b94d7db46d3fa66582c8fe3b02dabf72",
        .profile = .{
            .capabilities = .initMany(&.{ .streaming, .tools, .parallel_tool_calls, .thinking }),
            .settings = .initMany(&.{.reasoning_effort}),
            .reasoning_efforts = .initMany(&.{ .minimal, .low, .medium, .high }),
            .context_window = 272000,
            .max_output_tokens = 128000,
        },
    },
    .{
        .identity = .{ .provider = "openai-codex", .model = "gpt-5.6-terra" },
        .protocol_id = "openai-codex-responses",
        .aliases = &.{},
        .source_url = "https://github.com/badlogic/pi-mono/commit/73414d08b94d7db46d3fa66582c8fe3b02dabf72",
        .profile = .{
            .capabilities = .initMany(&.{ .streaming, .tools, .parallel_tool_calls, .thinking }),
            .settings = .initMany(&.{.reasoning_effort}),
            .reasoning_efforts = .initMany(&.{ .minimal, .low, .medium, .high }),
            .context_window = 272000,
            .max_output_tokens = 128000,
        },
    },
};

pub const value: catalog.Catalog = .{ .entries = &entries };

test "generated model catalog is valid and resolvable" {
    try value.validate();
    for (entries) |entry| {
        const resolved = value.resolve(entry.identity).?;
        try std.testing.expectEqualStrings(entry.identity.model, resolved.canonicalModelId());
        try std.testing.expect(entry.source_url != null);
    }
}
