const std = @import("std");
const catalog = @import("catalog");
const settings = catalog.model_settings;

const max_document_bytes = 1024 * 1024;

const Source = struct {
    version: u32,
    updated_at: []const u8,
    entries: []const SourceEntry,
};

const SourceEntry = struct {
    provider_id: []const u8,
    model_id: []const u8,
    protocol_id: []const u8,
    aliases: []const []const u8 = &.{},
    source_url: []const u8,
    profile: SourceProfile,
};

const SourceProfile = struct {
    capabilities: []const settings.Capability = &.{},
    settings: []const settings.Setting = &.{},
    reasoning_efforts: []const settings.ReasoningEffort = &.{},
    context_window: ?u64 = null,
    max_output_tokens: ?u64 = null,
};

pub fn main(init: std.process.Init) !void {
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    if (args.len != 4) return error.InvalidArguments;
    const source = try std.Io.Dir.cwd().readFileAlloc(
        init.io,
        args[2],
        init.gpa,
        .limited(max_document_bytes),
    );
    defer init.gpa.free(source);
    const generated = try generate(init.gpa, source);
    defer init.gpa.free(generated);

    if (std.mem.eql(u8, args[1], "check")) {
        const current = try std.Io.Dir.cwd().readFileAlloc(
            init.io,
            args[3],
            init.gpa,
            .limited(max_document_bytes),
        );
        defer init.gpa.free(current);
        if (!std.mem.eql(u8, generated, current)) return error.GeneratedSnapshotOutOfDate;
    } else if (std.mem.eql(u8, args[1], "update")) {
        var atomic = try std.Io.Dir.cwd().createFileAtomic(init.io, args[3], .{
            .make_path = true,
            .replace = true,
        });
        defer atomic.deinit(init.io);
        var buffer: [4096]u8 = undefined;
        var writer = atomic.file.writer(init.io, &buffer);
        try writer.interface.writeAll(generated);
        try writer.interface.flush();
        try atomic.file.sync(init.io);
        try atomic.replace(init.io);
    } else {
        return error.InvalidArguments;
    }
}

fn generate(allocator: std.mem.Allocator, source_text: []const u8) ![]u8 {
    return generateInner(allocator, source_text) catch |failure| switch (failure) {
        error.WriteFailed => error.OutOfMemory,
        else => |other| other,
    };
}

fn generateInner(allocator: std.mem.Allocator, source_text: []const u8) ![]u8 {
    const parsed = std.json.parseFromSlice(Source, allocator, source_text, .{
        .allocate = .alloc_always,
        .ignore_unknown_fields = false,
        .max_value_len = max_document_bytes,
    }) catch |failure| switch (failure) {
        error.OutOfMemory => return error.OutOfMemory,
        else => return error.InvalidModelCatalogSource,
    };
    defer parsed.deinit();
    const source = parsed.value;
    try validateSource(allocator, source);

    var output: std.Io.Writer.Allocating = .init(allocator);
    defer output.deinit();
    const writer = &output.writer;
    try writer.writeAll(
        \\//! Generated by `zig build update-model-catalog`; do not edit directly.
        \\
        \\const std = @import("std");
        \\const catalog = @import("model_catalog.zig");
        \\
    );
    try writer.print("pub const version: u32 = {};\n", .{source.version});
    try writer.print("pub const updated_at = \"{f}\";\n\n", .{std.zig.fmtString(source.updated_at)});
    try writer.writeAll("pub const entries = [_]catalog.Entry{\n");
    for (source.entries) |entry| try writeEntry(writer, entry);
    try writer.writeAll(
        \\};
        \\
        \\pub const value: catalog.Catalog = .{ .entries = &entries };
        \\
        \\test "generated model catalog is valid and resolvable" {
        \\    try value.validate();
        \\    for (entries) |entry| {
        \\        const resolved = value.resolve(entry.identity).?;
        \\        try std.testing.expectEqualStrings(entry.identity.model, resolved.canonicalModelId());
        \\        try std.testing.expect(entry.source_url != null);
        \\    }
        \\}
        \\
    );
    return output.toOwnedSlice();
}

fn validateSource(allocator: std.mem.Allocator, source: Source) !void {
    if (source.version != 1 or !validDate(source.updated_at)) return error.InvalidModelCatalogSource;
    const entries = try allocator.alloc(catalog.Entry, source.entries.len);
    defer allocator.free(entries);
    for (source.entries, 0..) |entry, index| {
        if (!std.mem.startsWith(u8, entry.source_url, "https://") or
            entry.source_url.len == "https://".len)
        {
            return error.InvalidModelCatalogSource;
        }
        if (index > 0 and compareEntry(source.entries[index - 1], entry) != .lt) {
            return error.InvalidModelCatalogSource;
        }
        try validateOrderedStrings(entry.aliases);
        try validateOrderedEnums(settings.Capability, entry.profile.capabilities);
        try validateOrderedEnums(settings.Setting, entry.profile.settings);
        try validateOrderedEnums(settings.ReasoningEffort, entry.profile.reasoning_efforts);
        entries[index] = .{
            .identity = .{ .provider = entry.provider_id, .model = entry.model_id },
            .protocol_id = entry.protocol_id,
            .aliases = entry.aliases,
            .source_url = entry.source_url,
            .profile = profileFromSource(entry.profile),
        };
    }
    _ = catalog.Catalog.init(entries) catch return error.InvalidModelCatalogSource;
}

fn compareEntry(left: SourceEntry, right: SourceEntry) std.math.Order {
    const provider_order = std.mem.order(u8, left.provider_id, right.provider_id);
    if (provider_order != .eq) return provider_order;
    return std.mem.order(u8, left.model_id, right.model_id);
}

fn validateOrderedStrings(values: []const []const u8) !void {
    for (values, 0..) |value, index| {
        if (value.len == 0) return error.InvalidModelCatalogSource;
        if (index > 0 and std.mem.order(u8, values[index - 1], value) != .lt) {
            return error.InvalidModelCatalogSource;
        }
    }
}

fn validateOrderedEnums(comptime T: type, values: []const T) !void {
    for (values, 0..) |value, index| {
        if (index > 0 and @intFromEnum(values[index - 1]) >= @intFromEnum(value)) {
            return error.InvalidModelCatalogSource;
        }
    }
}

fn profileFromSource(source: SourceProfile) settings.ModelProfile {
    return .{
        .capabilities = .initMany(source.capabilities),
        .settings = .initMany(source.settings),
        .reasoning_efforts = .initMany(source.reasoning_efforts),
        .context_window = source.context_window,
        .max_output_tokens = source.max_output_tokens,
    };
}

fn writeEntry(writer: *std.Io.Writer, entry: SourceEntry) !void {
    try writer.print(
        "    .{{\n        .identity = .{{ .provider = \"{f}\", .model = \"{f}\" }},\n",
        .{ std.zig.fmtString(entry.provider_id), std.zig.fmtString(entry.model_id) },
    );
    try writer.print("        .protocol_id = \"{f}\",\n", .{std.zig.fmtString(entry.protocol_id)});
    try writer.writeAll("        .aliases = &.{");
    if (entry.aliases.len > 1) try writer.writeByte(' ');
    for (entry.aliases, 0..) |alias, index| {
        if (index > 0) try writer.writeAll(", ");
        try writer.print("\"{f}\"", .{std.zig.fmtString(alias)});
    }
    if (entry.aliases.len > 1) try writer.writeByte(' ');
    try writer.writeAll("},\n");
    try writer.print("        .source_url = \"{f}\",\n", .{std.zig.fmtString(entry.source_url)});
    try writer.writeAll("        .profile = .{\n");
    try writeEnumSet(writer, "capabilities", entry.profile.capabilities);
    try writeEnumSet(writer, "settings", entry.profile.settings);
    try writeEnumSet(writer, "reasoning_efforts", entry.profile.reasoning_efforts);
    try writer.writeAll("            .context_window = ");
    try writeOptionalInteger(writer, entry.profile.context_window);
    try writer.writeAll(",\n            .max_output_tokens = ");
    try writeOptionalInteger(writer, entry.profile.max_output_tokens);
    try writer.writeAll(",\n        },\n    },\n");
}

fn writeEnumSet(writer: *std.Io.Writer, name: []const u8, values: anytype) !void {
    try writer.print("            .{s} = .initMany(&.{{", .{name});
    if (values.len > 1) try writer.writeByte(' ');
    for (values, 0..) |value, index| {
        if (index > 0) try writer.writeAll(", ");
        try writer.print(".{s}", .{@tagName(value)});
    }
    if (values.len > 1) try writer.writeByte(' ');
    try writer.writeAll("}),\n");
}

fn writeOptionalInteger(writer: *std.Io.Writer, value: ?u64) !void {
    if (value) |integer| try writer.print("{}", .{integer}) else try writer.writeAll("null");
}

fn validDate(value: []const u8) bool {
    if (value.len != 10 or value[4] != '-' or value[7] != '-') return false;
    for (value, 0..) |byte, index| {
        if (index == 4 or index == 7) continue;
        if (!std.ascii.isDigit(byte)) return false;
    }
    const year = (@as(u16, value[0] - '0') * 1000) +
        (@as(u16, value[1] - '0') * 100) +
        (@as(u16, value[2] - '0') * 10) + value[3] - '0';
    const month = (@as(u8, value[5] - '0') * 10) + value[6] - '0';
    const day = (@as(u8, value[8] - '0') * 10) + value[9] - '0';
    if (year == 0 or month == 0 or month > 12 or day == 0) return false;
    const leap = @mod(year, 4) == 0 and (@mod(year, 100) != 0 or @mod(year, 400) == 0);
    const maximum_day: u8 = switch (month) {
        2 => if (leap) 29 else 28,
        4, 6, 9, 11 => 30,
        else => 31,
    };
    return day <= maximum_day;
}

test "generator is deterministic and validates source ordering" {
    const fixture =
        \\{
        \\  "version": 1,
        \\  "updated_at": "2026-08-16",
        \\  "entries": [{
        \\    "provider_id": "test",
        \\    "model_id": "model",
        \\    "protocol_id": "test-protocol",
        \\    "aliases": ["alias"],
        \\    "source_url": "https://example.test/model",
        \\    "profile": {
        \\      "capabilities": ["tools"],
        \\      "context_window": 10,
        \\      "max_output_tokens": 2
        \\    }
        \\  }]
        \\}
    ;
    const first = try generate(std.testing.allocator, fixture);
    defer std.testing.allocator.free(first);
    const second = try generate(std.testing.allocator, fixture);
    defer std.testing.allocator.free(second);
    try std.testing.expectEqualStrings(first, second);
    try std.testing.expect(std.mem.indexOf(u8, first, ".capabilities = .initMany(&.{.tools})") != null);
    try std.testing.expect(std.mem.indexOf(u8, first, ".context_window = 10") != null);

    try std.testing.expectError(error.InvalidModelCatalogSource, generate(
        std.testing.allocator,
        "{\"version\":2,\"updated_at\":\"2026-08-16\",\"entries\":[]}",
    ));
    try std.testing.expectError(error.InvalidModelCatalogSource, generate(
        std.testing.allocator,
        "{\"version\":1,\"updated_at\":\"2026-02-29\",\"entries\":[]}",
    ));
    try std.testing.expectError(error.InvalidModelCatalogSource, generate(
        std.testing.allocator,
        "{\"version\":1,\"updated_at\":\"2026-08-16\",\"unknown\":true,\"entries\":[]}",
    ));
    const unsorted =
        \\{"version":1,"updated_at":"2026-08-16","entries":[
        \\  {"provider_id":"z","model_id":"one","source_url":"https://example.test/z","profile":{}},
        \\  {"provider_id":"a","model_id":"one","source_url":"https://example.test/a","profile":{}}
        \\]}
    ;
    try std.testing.expectError(
        error.InvalidModelCatalogSource,
        generate(std.testing.allocator, unsorted),
    );
}

test "generator releases every allocation" {
    const fixture =
        \\{
        \\  "version": 1,
        \\  "updated_at": "2026-08-16",
        \\  "entries": [{
        \\    "provider_id": "test",
        \\    "model_id": "model",
        \\    "protocol_id": "test-protocol",
        \\    "source_url": "https://example.test/model",
        \\    "profile": {}
        \\  }]
        \\}
    ;
    try std.testing.checkAllAllocationFailures(std.testing.allocator, struct {
        fn exercise(allocator: std.mem.Allocator, source: []const u8) !void {
            const generated = try generate(allocator, source);
            defer allocator.free(generated);
        }
    }.exercise, .{fixture});
}
